import type {Question,QuestionKind,QuestionPart,Diagram} from '../types';
import {base,sources,rubric,activity} from './software-support';

type OpenKind=Exclude<QuestionKind,'choice'|'compound'>;
function task(round:number,n:number,kind:OpenKind,source:string,title:string,prompt:string,modelAnswer:string,explanation:string,criteria:[string,number][],extra:Partial<Question>={}):Question{
 return {...base(round,n,source,title),kind,points:n<18?30:50,prompt,modelAnswer,explanation,keyPoints:[explanation],rubric:rubric(criteria),sources:sources(round,source),...extra};
}
function part(id:string,title:string,kind:QuestionPart['kind'],points:number,prompt:string,modelAnswer:string,explanation:string,criteria:[string,number][],extra:Partial<QuestionPart>={}):QuestionPart{
 return {id,title,kind,points,prompt,modelAnswer,explanation,rubric:rubric(criteria),...extra};
}
function integrated(round:number,title:string,prompt:string,source:string,parts:QuestionPart[]):Question{
 return {...base(round,21,source,title),kind:'compound',points:80,prompt,parts,explanation:'각 소문항의 모범답안과 기준을 확인하고 설명·코드의 근거를 함께 평가한다.',keyPoints:parts.map(p=>p.explanation),sources:sources(round,source)};
}
const rental=activity(['차량 대여 가능 여부 확인'],{after:0,label:'대여 가능?',yes:'대여 처리',no:'예약 처리'});
const book:Diagram={nodes:[{id:'b',x:400,y:140,shape:'class',label:'Book {abstract}\n-title: String\n-author: String\n+setTitle(t:String):void\n{abstract}\n+setAuthor(a:String):void\n{abstract}'},{id:'e',x:400,y:400,shape:'class',label:'EBook\n+setTitle(t:String):void\n+setAuthor(a:String):void'}],edges:[{id:'i',from:'e',to:'b',kind:'inheritance'}]};
const orderClasses:Diagram={nodes:[{id:'o',x:180,y:250,shape:'class',label:'Order\n-id: String\n+total(): int'},{id:'l',x:600,y:250,shape:'class',label:'OrderLine\n-price: int\n-quantity: int\n+subtotal(): int'}],edges:[{id:'ol',from:'o',to:'l',kind:'composition',label:'1 / 1..*'}]};
const policy:Diagram={nodes:[{id:'s',x:150,y:200,shape:'class',label:'Checkout\n-policy: DiscountPolicy\n+total(p:int):int'},{id:'p',x:500,y:120,shape:'class',label:'DiscountPolicy {abstract}\n+apply(p:int):int\n{abstract}'},{id:'f',x:360,y:380,shape:'class',label:'FixedDiscount\n+apply(p:int):int'},{id:'n',x:620,y:380,shape:'class',label:'NoDiscount\n+apply(p:int):int'}],edges:[{id:'sp',from:'s',to:'p',kind:'arrow',label:'사용'},{id:'fp',from:'f',to:'p',kind:'inheritance'},{id:'np',from:'n',to:'p',kind:'inheritance'}]};
const validationFlow:Diagram={nodes:[{id:'s',x:380,y:20,shape:'start',label:'시작'},{id:'i',x:300,y:90,shape:'action',label:'수량 입력'},{id:'d',x:300,y:200,shape:'decision',label:'1 이상10 이하?'},{id:'e',x:130,y:320,shape:'action',label:'오류 안내'},{id:'a',x:500,y:320,shape:'action',label:'주문 접수'},{id:'f',x:570,y:490,shape:'end',label:'종료'}],edges:[{id:'si',from:'s',to:'i'},{id:'id',from:'i',to:'d'},{id:'de',from:'d',to:'e',label:'[아니요]'},{id:'ei',from:'e',to:'i'},{id:'da',from:'d',to:'a',label:'[예]'},{id:'af',from:'a',to:'f'}]};
export const softwareOpen:Question[]=[
 task(1,16,'essay','design','모듈 경계 검토','서로 무관한 기능을 한 모듈에 넣고 다른 모듈의 내부 변수를 직접 변경하는 설계가 있다. 응집도와 결합도의 관점에서 문제점과 개선 방향을 각각 설명하시오.','무관한 기능의 집합은 응집도가 낮아 서로 다른 이유로 변경된다. 타 모듈 내부 변수 직접 변경은 내용 결합을 높여 구현 변경이 다른 모듈로 전파된다. 기능·변경 이유에 따라 모듈을 분리하고, 내부 상태를 숨긴 채 필요한 값만 공개 인터페이스로 전달하도록 바꾼다.','좋은 모듈화는 내부 요소의 목적을 모으고 외부가 내부 구현을 알아야 하는 정도를 낮춘다.',[['낮은 응집도의 원인과 영향 설명',10],['내용 결합의 원인과 영향 설명',10],['책임 분리와 인터페이스 개선 제시',10]]),
 task(1,17,'essay','test','테스트 조합 평가','결정식 A || B를 (참,참), (거짓,거짓) 두 조합으로 시험했다. 조건 커버리지, 결정 커버리지, MC/DC의 충족 여부와 이유를 설명하고 MC/DC를 만족하는3개 조합을 제안하시오.','A와B가 각각 참·거짓을 경험해 조건 커버리지는 충족한다. 결정 결과도 참·거짓이므로 결정 커버리지를 충족한다. 그러나 두 조건이 동시에 바뀌어 독립적인 영향은 입증하지 못하므로 MC/DC는 불충족이다. (참,거짓),(거짓,거짓),(거짓,참)을 사용하면 B를 거짓으로 고정한 A의 영향과 A를 거짓으로 고정한 B의 영향을 각각 보인다.','조건별 결과, 전체 결정 결과, 독립적 영향은 서로 다른 기준이다.',[['조건·결정 커버리지 판정',10],['MC/DC 불충족 근거',10],['올바른3개 조합과 독립 영향 설명',10]]),
 task(1,18,'code','algorithm','반복 계산으로 변환','Python factorial(n)을 작성하시오. n은0 이상의 정수이며0!은1이다. 재귀를 사용하지 말고 누적 곱으로 계산하시오.','def factorial(n):\n    result = 1\n    for value in range(2, n + 1):\n        result *= value\n    return result','누적값을1로 초기화하면 n=0,1에서 반복 없이1을 반환한다. n까지 포함해 곱한다.',[['누적값1 초기화',10],['2부터 n까지 올바른 반복',20],['곱 누적과 결과 반환',15],['재귀 없이0·1 처리',5]],{language:'python',starterCode:'def factorial(n):\n    # n은 0 이상의 정수\n    pass'}),
 task(1,19,'diagram','activity','차량 처리 흐름','차량 대여 가능 여부를 확인한다. 가능하면 대여 처리, 불가능하면 예약 처리를 수행한다. 선택한 한 경로를 마치면 흐름을 종료한다. 시작·종료·행동·결정·병합 노드와 조건을 포함한 활동도를 그리시오.','시작→대여 가능 여부 확인→결정. [예]→대여 처리, [아니요]→예약 처리. 두 대안은 병합 노드로 모은 뒤 종료한다.','상호 배타적 선택은 결정·병합 마름모를 사용한다. 병렬 실행이 아니므로 fork/join 막대를 쓰지 않는다.',[['시작·종료와 확인 행동',10],['결정 노드와 상호 배타 조건',15],['대여·예약 두 행동',15],['대안 경로 병합 및 올바른 연결',10]],{modelDiagram:rental}),
 task(1,20,'short','algorithm','중위 결과 계산','빈 이진 탐색 트리에40,20,60,10,30,50,70을 삽입한다. 두 자식 노드 삭제 시 중위 후속자로 대체하여40을 삭제한 뒤25를 삽입한다. 최종 트리의 중위 순회 결과를 쉼표로 작성하시오.','10,20,25,30,50,60,70','40 삭제 시 후속자50으로 대체하고 원래50 노드를 제거한다.25는30의 왼쪽에 삽입된다. BST 중위 순회는 키 오름차순이다.',[['후속자50으로 삭제 처리',20],['25 삽입 위치 이해',15],['최종 중위 결과 정확',15]],{answer:'10,20,25,30,50,60,70',acceptedAnswers:['10,20,25,30,50,60,70','10 20 25 30 50 60 70','10 → 20 → 25 → 30 → 50 → 60 → 70']}),
 integrated(1,'도서 모델 구현','전자 도서 모듈을 설계한다. Book은 추상 클래스이고 title과 author는 private String 속성이다. public 추상 메서드 setTitle(String),setAuthor(String)는 반환값이 없다. EBook은 Book을 상속하며 두 메서드를 구현한다. 다음 과제를 수행하시오.','object',[
 part('a','접근과 추상성', 'essay',20,'private 속성과 public 추상 메서드의 의미를 각각 설명하시오.','private 속성은 선언 클래스 외부에서 직접 접근할 수 없다. public 추상 메서드는 외부에 공개하는 계약이며 본문이 없고 구체 하위 클래스가 구현해야 한다.','가시성과 구현 여부는 별개의 속성이다.',[['private 의미',10],['public·abstract 의미',10]]),
 part('b','클래스 구조','diagram',30,'Book과 EBook의 UML 클래스 다이어그램을 그리시오.','Book에 두 -속성과 두 +추상 연산을 표시한다. EBook에 두 구현 연산을 표시하고 EBook에서 Book으로 실선 빈 삼각형을 연결한다.','상속 화살표는 상위 클래스Book을 향한다.',[['속성·추상 연산 표기',15],['구체 연산과 일반화 방향',15]],{modelDiagram:book}),
 part('c','추상 클래스 선언','code',30,'Book의 Java 선언만 작성하시오. EBook 구현은 요구하지 않는다.','public abstract class Book {\n    private String title;\n    private String author;\n    public abstract void setTitle(String title);\n    public abstract void setAuthor(String author);\n}','추상 클래스와 추상 메서드에는 abstract가 필요하며 추상 메서드는 본문 없이 세미콜론으로 끝난다.',[['추상 클래스·private 속성',15],['public 추상 메서드 두 개',15]],{language:'java',starterCode:'public abstract class Book {\n    // 속성과 추상 연산을 작성하세요.\n}'})]),

 task(2,16,'essay','algorithm','두 탐색 전략 비교','BFS와 DFS의 방문 방식, 사용하는 대표 자료구조, 가중치 없는 그래프의 최단 경로와의 관계를 비교하시오.','BFS는 시작점에서 가까운 거리부터 넓게 방문하며 큐를 사용한다. 가중치 없는 그래프에서 첫 발견 경로는 최소 간선 수 경로다. DFS는 한 경로를 깊게 진행하다 되돌아오며 스택이나 재귀 호출을 사용한다. DFS의 첫 발견 경로가 최단이라는 보장은 없다. 두 방법 모두 그래프에서 방문 표시로 중복·순환을 처리한다.','깊이 우선·너비 우선의 차이는 다음에 처리할 정점을 관리하는 방식에서 나온다.',[['방문 순서 비교',10],['큐·스택/재귀 구분',10],['최단 경로 성질과 방문 표시',10]]),
 task(2,17,'essay','algorithm','저장 구조 선택','정점10000개, 간선20000개인 그래프에서 각 정점의 이웃을 자주 순회한다. 인접 행렬과 인접 리스트의 공간 및 이웃 순회 비용을 비교하고 적절한 선택을 설명하시오.','인접 행렬은 정점 쌍마다 공간을 두어 O(V²)이고 한 정점의 이웃을 찾으려면 행을 O(V) 검사한다. 인접 리스트는 O(V+E) 공간이며 이웃 순회는 해당 정점의 차수에 비례한다. 이 그래프는 가능한 정점 쌍에 비해 간선이 적으므로 리스트가 공간과 이웃 순회에 유리하다. 단, 특정 간선 존재를 즉시 조회할 때는 행렬의 O(1) 접근이 장점이다.','자료구조는 입력의 희소성과 필요한 연산을 함께 보고 선택한다.',[['두 공간복잡도 비교',10],['이웃 순회 비용 비교',10],['희소성 근거와 행렬 장점',10]]),
 task(2,18,'code','algorithm','정렬 루틴 완성','Python bubble_sort(values)를 작성하시오. 입력 리스트를 오름차순으로 직접 정렬해 반환하고, 한 순회에서 교환이 없으면 일찍 종료하시오.','def bubble_sort(values):\n    for end in range(len(values) - 1, 0, -1):\n        changed = False\n        for i in range(end):\n            if values[i] > values[i + 1]:\n                values[i], values[i + 1] = values[i + 1], values[i]\n                changed = True\n        if not changed:\n            break\n    return values','매 순회 최댓값이 뒤로 이동한다. 비교 범위를 줄이고 무교환 시 종료한다.',[['인접 비교와 교환',20],['유효한 반복 범위와 빈 리스트 처리',10],['무교환 조기 종료',15],['리스트 반환',5]],{language:'python',starterCode:'def bubble_sort(values):\n    pass'}),
 task(2,19,'diagram','algorithm','검색 과정의 흐름','배열을 앞에서부터 선형 검색한다. 인덱스 i=0으로 시작한다. i가 길이 미만이면 값을 비교하여 같으면 i를 반환·종료한다. 다르면 i를1 증가시켜 반복한다. 범위를 벗어나면 -1을 반환한다. 활동도를 그리시오.','시작→i=0→i<len? 결정. [아니요]→-1반환→종료. [예]→arr[i]==target? 결정. [예]→i반환→종료. [아니요]→i증가→범위 결정으로 돌아간다.','배열 접근 전에 범위를 확인해야 빈 배열과 끝까지 못 찾은 경우를 안전하게 처리한다.',[['초기화와 범위 결정',15],['일치 결정·성공 반환',15],['증가 후 반복 연결',10],['실패 반환과 종료',10]],{modelDiagram:{nodes:[{id:'s',x:30,y:20,label:'시작',shape:'start'},{id:'i',x:130,y:90,label:'i = 0',shape:'action'},{id:'d',x:340,y:90,label:'i < len(arr)?',shape:'decision'},{id:'v',x:340,y:250,label:'arr[i] == target?',shape:'decision'},{id:'inc',x:130,y:380,label:'i = i + 1',shape:'action'},{id:'yes',x:640,y:250,label:'i 반환',shape:'action'},{id:'no',x:640,y:90,label:'-1 반환',shape:'action'},{id:'f',x:610,y:470,label:'종료',shape:'end'}],edges:[{id:'a',from:'s',to:'i'},{id:'b',from:'i',to:'d'},{id:'c',from:'d',to:'v',label:'[예]'},{id:'d1',from:'d',to:'no',label:'[아니요]'},{id:'e',from:'v',to:'yes',label:'[예]'},{id:'f1',from:'v',to:'inc',label:'[아니요]'},{id:'g',from:'inc',to:'d'},{id:'h',from:'yes',to:'f'},{id:'j',from:'no',to:'f'}]}}),
 task(2,20,'short','algorithm','이진 검색의 비교','배열 [3,7,11,15,19,23,27]에서23을 검색한다. low=0,high=6이고 mid=(low+high)//2이며 일치 여부를 중간 원소와 한 번 비교한다고 셀 때, 비교한 원소를 순서대로 쓰시오.','15,23','처음 mid=3이므로15와 비교한다.23이 크므로 low=4,high=6으로 바꾸면 mid=5이고23을 찾는다.',[['첫 중간값15',15],['탐색 구간4..6 계산',20],['다음 비교23 및 종료',15]],{answer:'15,23',acceptedAnswers:['15,23','15 23','15 → 23']}),
 integrated(2,'배송 경로 점검','모든 도로 비용이1인 무방향 그래프다. 간선은 A-B,A-C,B-D,C-D,D-E이다. 이웃은 알파벳 순서로 처리한다. A에서 탐색한다.','algorithm',[
 part('a','방문 순서','short',20,'BFS 방문 순서를 쓰시오.','A,B,C,D,E','D는 처음 큐에 넣을 때 방문 표시하여 중복 삽입을 막는다.',[['A,B,C 순서',10],['D를 중복 없이E보다 먼저 처리',10]],{answer:'A,B,C,D,E',acceptedAnswers:['A,B,C,D,E','A B C D E']}),
 part('b','탐색 구현','code',30,'graph는 이웃 리스트 사전이다. 시작 정점에서 각 정점까지 최소 간선 수를 반환하는 distances(graph,start)를 Python으로 작성하시오.','from collections import deque\ndef distances(graph, start):\n    dist = {start: 0}\n    queue = deque([start])\n    while queue:\n        v = queue.popleft()\n        for u in graph.get(v, []):\n            if u not in dist:\n                dist[u] = dist[v] + 1\n                queue.append(u)\n    return dist','큐에 넣을 때 거리를 기록하면 같은 정점이 중복 예약되지 않는다.',[['큐의 FIFO 처리',10],['방문·거리 갱신',15],['결과 반환',5]],{language:'python'}),
 part('c','조건 변화 판단','essay',30,'도로 비용이1이 아니라 서로 다른 양수가 되면 BFS의 첫 발견 경로를 최저 비용 경로라고 단정할 수 있는가? 이유와 대안을 설명하시오.','단정할 수 없다. BFS는 간선 수를 최소화할 뿐 가중치 합을 최소화하지 않는다. 모든 가중치가 음수가 아니라면 다익스트라 알고리즘으로 누적 비용이 작은 정점을 우선 처리하는 방법을 사용할 수 있다.','최단의 기준이 간선 수인지 가중치 합인지 구분해야 한다.',[['BFS 보장 한계',15],['비음수 조건과 대안',15]])]),

 task(3,16,'essay','object','상속과 포함 선택','알림 서비스는 이메일·문자 발송 방식을 실행 중 교체해야 한다. 모든 조합을 상속 클래스로 만드는 방식의 문제와 합성·인터페이스를 이용한 대안을 설명하시오.','조합별 상속은 클래스 수를 늘리고 새 발송 방식 추가·교체를 어렵게 한다. Sender 인터페이스와 EmailSender,SmsSender 구현을 두고 NotificationService가 Sender를 필드로 받아 위임하게 한다. 서비스 코드는 계약에 의존하며 주입한 객체를 교체해 행동을 바꾼다. 상속은 실제 하위 타입 관계일 때 선택한다.','변하는 행동을 객체로 분리하여 위임하면 조합과 교체가 쉬워진다.',[['상속 조합 증가·교체 한계',10],['인터페이스와 구현 분리',10],['주입·위임 및 상속 판단 기준',10]]),
 task(3,17,'essay','object','멤버 접근 구별','Java에서 오버로딩과 오버라이딩을 매개변수·상속·다형성 관점에서 비교하고 각각 예를 드시오.','오버로딩은 같은 이름을 서로 다른 매개변수 목록으로 선언하는 것으로 print()와 print(String)이 예다. 반환형만 바꾸어 구분할 수 없다. 오버라이딩은 하위 클래스가 상속한 동일 시그니처의 인스턴스 메서드를 재정의하는 것으로 Animal.sound()를 Dog.sound()가 구현하는 예다. 상위 타입 참조라도 실제 객체에 따라 재정의 메서드가 실행될 수 있다.','오버로딩은 호출 시그니처 선택이고 오버라이딩은 상속 계약을 유지한 구현 재정의다.',[['오버로딩 정의·예',10],['오버라이딩 정의·예',10],['반환형만 오버로딩 불가·동적 다형성',10]]),
 task(3,18,'code','object','입력별 동작 추가','Robot에 public void grab()이 있다. CoffeeRobot extends Robot을 작성하고 public void grab(int number)를 추가하시오.1이면 "컵을 잡다.", 나머지는 "그라인더를 잡다."를 출력한다. 기존 grab()을 재정의하라는 요구는 아니다.','public class CoffeeRobot extends Robot {\n    public void grab(int number) {\n        if (number == 1) {\n            System.out.println("컵을 잡다.");\n        } else {\n            System.out.println("그라인더를 잡다.");\n        }\n    }\n}','매개변수를 추가한 grab(int)는 grab()과 다른 시그니처의 오버로딩이다. @Override를 붙이면 안 된다.',[['상속과 public void 시그니처',15],['number==1 조건',15],['두 출력 문구와 분기',15],['오버로딩을 유효한 문법으로 작성',5]],{language:'java',starterCode:'public class CoffeeRobot extends Robot {\n    // grab(int number)를 작성하세요.\n}'}),
 task(3,19,'diagram','object','주문과 항목 구조','Order는 private id:String과 public total():int를 갖는다. OrderLine은 private price:int,quantity:int와 public subtotal():int를 갖는다. 한 주문은1개 이상 항목을 배타적으로 소유하며 주문 삭제 시 항목도 사라진다. 관계와 다중성을 포함하여 클래스 다이어그램을 그리시오.','Order에 -id:String,+total():int를, OrderLine에 -price:int,-quantity:int,+subtotal():int를 적는다. Order쪽에 속이 찬 마름모를 두고 OrderLine과 합성으로 연결한다. Order쪽1, 항목쪽1..*를 표시한다.','필드가 있다는 사실만으로 합성을 단정하지 않고 문제에 명시된 배타 소유·수명 조건을 사용한다.',[['두 클래스의 속성·연산',20],['Order쪽 합성 마름모',15],['1과1..* 다중성',15]],{modelDiagram:orderClasses}),
 task(3,20,'short','object','동적 호출 결과','Java에서 Base b = new Child(); b.run();을 실행한다. Base.run()은 "BASE", Child의 오버라이딩한 public void run()은 "CHILD"를 출력한다. 두 메서드는 static이 아니다. 출력은?','CHILD','인스턴스 메서드의 오버라이딩은 실제 객체 타입Child의 구현을 호출한다.',[['참조 타입과 실제 객체 타입 구분',20],['인스턴스 메서드 동적 바인딩 설명',20],['CHILD 출력',10]],{answer:'CHILD',acceptedAnswers:['CHILD','"CHILD"']}),
 integrated(3,'주문 할인 정책 분리','Checkout 안의 할인 조건문이 커지고 있다. 추상 DiscountPolicy에는 apply(price:int):int가 있고 FixedDiscount와 NoDiscount가 구현한다. Checkout은 전달받은 정책을 사용한다.','object',[
 part('a','설계 원칙','essay',20,'이 구조가 할인 추가 시 기존 코드를 덜 수정하도록 돕는 이유를 설명하시오.','정책별 구현을 같은 추상 계약으로 분리하므로 Checkout은 구체 종류를 검사하지 않고 apply만 호출한다. 새 정책은 구현 추가와 구성 변경으로 연결할 수 있어 개방·폐쇄 원칙에 부합한다.','확장 지점을 인터페이스로 만들고 조건 분기 변경을 줄인다.',[['변경 지점 분리',10],['원칙과 효과 연결',10]]),
 part('b','구조 그림','diagram',30,'위 클래스 관계를 그리시오. DiscountPolicy는 추상 클래스로 표현하시오.','Checkout→DiscountPolicy 사용 관계, FixedDiscount와 NoDiscount→DiscountPolicy 일반화 관계를 표시한다.','사용 관계와 일반화는 서로 다른 선이다.',[['추상 계약과 두 구현',15],['사용 및 일반화 방향',15]],{modelDiagram:policy}),
 part('c','금액 규칙 구현','code',30,'FixedDiscount가1000원을 빼되 결과가0 미만이면0을 반환하도록 Java apply를 구현하시오. 입력은0 이상의 int이다.','public class FixedDiscount extends DiscountPolicy {\n    @Override\n    public int apply(int price) {\n        return Math.max(0, price - 1000);\n    }\n}','하한0을 지켜 음수 결제금액을 방지한다.',[['올바른 상속·오버라이딩',10],['1000원 차감 및0 하한',20]],{language:'java'})]),

 task(4,16,'essay','test','테스트 수준의 역할','단위 테스트가 모두 통과했는데 결제 서비스와 주문 서비스 사이 데이터 형식 불일치가 발생했다. 단위·통합·시스템 테스트의 범위를 비교하고 단위 테스트만으로 충분하지 않은 이유를 설명하시오.','단위 테스트는 작은 함수·클래스를 격리해 확인한다. 통합 테스트는 모듈 사이 인터페이스와 데이터 교환을 검증한다. 시스템 테스트는 통합된 전체 시스템이 기능·비기능 요구를 만족하는지 확인한다. 각 단위가 자체 가정에서 맞아도 실제 연결의 필드·단위·오류 계약이 다를 수 있어 통합 검증이 필요하다.','각 수준은 서로 다른 결함 범위를 다루므로 한 수준의 통과가 다른 수준을 대체하지 않는다.',[['단위 범위',10],['통합·시스템 범위',10],['사례와 불충분성 연결',10]]),
 task(4,17,'essay','test','실행률과 품질 구분','팀장이 “문장 커버리지가100%이므로 결함이 없다”고 주장한다. 왜 잘못된 결론인지 설명하고 추가 검증 관점3가지를 제안하시오.','문장 커버리지는 실행 가능한 문장을 실행했다는 뜻이다. 모든 분기·조건 조합, 경계 입력, 누락된 요구와 출력의 정확성을 보장하지 않는다. 추가로 경계·동등 클래스 테스트, 결정·조건 검증, 요구 기반 인수 테스트를 수행한다. 성능·보안 등 비기능 요구 시험도 필요하다.','실행 범위 지표와 올바름의 증거를 구분한다.',[['커버리지의 의미',10],['결함 없음 추론의 한계',10],['구체적 추가 관점3가지',10]]),
 task(4,18,'code','test','경계 동작 검증','Python valid_quantity(n)은 정수 n이1~10이면 True, 아니면 False를 반환해야 한다. 구현과 assert를 사용한 경계 테스트4개(0,1,10,11)를 작성하시오.','def valid_quantity(n):\n    return 1 <= n <= 10\n\nassert valid_quantity(0) is False\nassert valid_quantity(1) is True\nassert valid_quantity(10) is True\nassert valid_quantity(11) is False','양쪽 경계의 바로 바깥과 경계를 포함해야 >와>= 오류를 구분할 수 있다.',[['올바른 포함 범위 구현',20],['0·1 테스트',15],['10·11 테스트',15]],{language:'python',starterCode:'def valid_quantity(n):\n    pass\n\n# 경계 테스트를 작성하세요.'}),
 task(4,19,'diagram','activity','입력 오류 회복 흐름','수량을 입력받아1~10 범위인지 검사한다. 유효하면 주문을 접수하고 종료한다. 무효하면 오류를 안내하고 다시 입력받는다. 활동도를 그리시오.','시작→수량입력→범위 결정. [예] 주문접수→종료. [아니요] 오류안내→수량입력으로 복귀.','재입력 루프는 무효 경로만 돌아가고 유효 경로는 종료하도록 한다.',[['입력·검증 행동과 결정',15],['유효 경로·종료',15],['무효 안내·재입력 루프',15],['가드 조건 표시',5]],{modelDiagram:validationFlow}),
 task(4,20,'short','test','분기 결과 비율','서로 독립된 if문이3개이며 각 if의 참·거짓을 하나의 결정 결과로 센다. 테스트 집합이 총6개 가능한 결과 중5개를 실행했다. 결정 커버리지를 분수로 쓰시오.','5/6','각 if가2개 결과를 가지므로 분모는3×2=6이며 실행된 결과5개를 나눈다. 약83.33%다.',[['총 결과 수6',20],['실행 결과 수5 적용',15],['5/6 계산',15]],{answer:'5/6',acceptedAnswers:['5/6','83.33%','약83.33%','약 83.33%']}),
 integrated(4,'쿠폰 경계와 회귀','쿠폰은 회원이고 구매금액이10000원 이상이면 적용한다. 금액은0 이상의 정수다. 기존 코드는 member and amount > 10000으로 작성되어 있다.','test',[
 part('a','결함 재현','short',20,'회원 여부와 금액 한 쌍으로 결함을 드러내시오.','True,10000','정확히10000원에서 명세는True이고 잘못된 구현은False다.',[['회원 조건 참',10],['금액10000 선택',10]],{answer:'True,10000',acceptedAnswers:['True,10000','true,10000','참,10000','회원,10000']}),
 part('b','수정과 테스트','code',30,'can_use(member,amount)를 수정하고 비회원·경계 미만·경계의 테스트를 작성하시오.','def can_use(member, amount):\n    return member and amount >= 10000\n\nassert can_use(False, 10000) is False\nassert can_use(True, 9999) is False\nassert can_use(True, 10000) is True','회원 조건과 금액 조건 각각을 변화시켜 확인한다.',[['조건 수정',10],['세 테스트 입력·예상값',20]],{language:'python'}),
 part('c','회귀 범위','essay',30,'이 함수를 장바구니·즉시구매·정기주문에서 공유한다. 수정 후 필요한 회귀 검증과 그 이유를 설명하시오.','세 호출 경로가 넘기는 회원·금액의 의미와 쿠폰 적용 결과를 확인한다. 경계값 외에도 비회원과 정상 고액 입력을 확인하고 할인 후 총액 및 중복 쿠폰 규칙이 깨지지 않았는지 검증한다. 공통 함수 변경은 모든 사용 경로로 영향을 전파할 수 있기 때문이다.','함수 단위 검증과 호출 경로의 통합 검증을 함께 한다.',[['공유 경로3개와 영향',10],['경계·비회원·정상 입력',10],['총액 등 주변 규칙 회귀',10]])]),

 task(5,16,'essay','process','제품 피드백과 팀 개선','스프린트 리뷰와 회고의 목적·참여 초점·산출물의 차이를 설명하시오.','리뷰는 완성된 제품 증분을 이해관계자와 살펴보고 요구·가치·다음 방향에 대한 피드백을 얻는다. 회고는 팀의 협업·도구·과정에서 잘된 점과 문제를 살펴 다음 반복의 개선 행동을 정한다. 리뷰의 결과는 제품 백로그 조정으로, 회고의 결과는 구체적인 작업 방식 개선으로 이어질 수 있다.','제품을 검토하는 활동과 제품을 만드는 과정을 개선하는 활동을 구분한다.',[['리뷰 목적·제품 초점',10],['회고 목적·과정 초점',10],['각 결과의 활용',10]]),
 task(5,17,'essay','requirements','요구 변경의 영향','이미 승인된 예약 요구에 “대기 예약을 허용하자”는 변경이 들어왔다. 개발 전에 어떤 영향을 검토하고 어떤 산출물을 함께 갱신해야 하는지 설명하시오.','업무 규칙과 우선순위를 확인하고 예약 상태·DB구조·API·화면·알림·동시성에 미치는 영향을 분석한다. 일정·비용·위험을 검토해 변경을 승인한다. 승인 후 요구 명세, 설계, 구현, 테스트 및 추적성 정보를 일관되게 갱신하고 대기에서 확정으로 전환되는 예외도 검증한다.','변경은 코드 한 곳의 수정이 아니라 연결된 산출물의 일관성 관리다.',[['업무·기술 영향 분석',10],['일정·위험과 승인',10],['산출물 갱신·회귀 검증',10]]),
 task(5,18,'code','requirements','업무 규칙 구현','Python can_cancel(status,minutes)를 작성하시오. status가 "PAID"이고 결제 후 경과시간이0 이상30 이하일 때만 True이다. 다른 경우 False다.','def can_cancel(status, minutes):\n    return status == "PAID" and 0 <= minutes <= 30','상태 조건과 시간 구간을 모두 만족해야 한다. 음수 경과시간과30분 초과도 거부한다.',[['상태 일치 검사',15],['0..30 포함 검사',20],['논리곱 및 반환',15]],{language:'python',starterCode:'def can_cancel(status, minutes):\n    pass'}),
 task(5,19,'diagram','activity','변경 검토 절차','변경 요청을 접수한 후 영향을 분석한다. 승인되면 구현·테스트하고 종료한다. 거절되면 사유를 기록하고 종료한다. 병렬 동작 없이 활동도를 작성하시오.','시작→변경접수→영향분석→승인? [예] 구현·테스트, [아니요] 거절사유기록. 대안 경로를 병합해 종료한다.','승인 판단 전에 영향을 분석하고 결정의 양쪽 결과를 모두 표현한다.',[['접수·영향 분석 순서',15],['승인 결정·가드',15],['두 후속 행동',10],['병합·종료',10]],{modelDiagram:{nodes:[{id:'s',x:400,y:20,label:'시작',shape:'start'},{id:'a',x:310,y:70,label:'변경 요청 접수',shape:'action'},{id:'b',x:310,y:150,label:'영향 분석',shape:'action'},{id:'d',x:310,y:230,label:'승인?',shape:'decision'},{id:'y',x:170,y:340,label:'구현 및 테스트',shape:'action'},{id:'n',x:530,y:340,label:'거절 사유 기록',shape:'action'},{id:'m',x:320,y:430,label:'',shape:'decision'},{id:'f',x:380,y:540,label:'종료',shape:'end'}],edges:[{id:'1',from:'s',to:'a'},{id:'2',from:'a',to:'b'},{id:'3',from:'b',to:'d'},{id:'4',from:'d',to:'y',label:'[예]'},{id:'5',from:'d',to:'n',label:'[아니요]'},{id:'6',from:'y',to:'m'},{id:'7',from:'n',to:'m'},{id:'8',from:'m',to:'f'}]}}),
 task(5,20,'short','requirements','추적표 영향 범위','추적표가 R1→M1,M2; R2→M2,M3; R3→M4이다. 변경된 요구는R1과R2이며 영향 모듈의 합집합을 구한다. 모듈 ID를 중복 없이 오름차순으로 쓰시오.','M1,M2,M3','R1의 M1,M2와R2의 M2,M3를 합치고 중복 M2를 제거한다.',[['R1 연결 모듈 확인',15],['R2 연결 모듈 확인',15],['합집합·중복 제거',20]],{answer:'M1,M2,M3',acceptedAnswers:['M1,M2,M3','M1 M2 M3']}),
 integrated(5,'작은 제품 증분 계획','도서 예약 서비스를3주 안에 시험 운영한다. 필수 가치는 도서 검색과 예약이며 추천·SNS 공유는 후순위다. 매주 작동하는 증분을 제공한다.','process',[
 part('a','초기 범위','essay',20,'첫 증분의 범위를 선정하고 이유를 설명하시오.','도서 검색·가용 여부 확인·기본 예약까지 최소한의 한 사용자 흐름을 완성한다. 추천·공유는 뒤로 미뤄 핵심 가치와 업무 규칙을 빨리 확인한다.','기술 계층만 완성하기보다 작동하는 사용자 과제를 제공한다.',[['핵심 흐름 선정',10],['피드백·우선순위 이유',10]]),
 part('b','인수 조건','essay',30,'예약 성공·실패를 검증 가능한 조건3개로 작성하시오.','①가용 도서와 로그인 사용자가 주어지면 예약 후 예약번호를 받는다.②재고0인 도서는 새 확정 예약을 만들지 않고 불가를 안내한다.③같은 사용자가 같은 도서를 중복 예약하면 두 번째 확정 예약을 만들지 않는다.','초기 조건·행동·결과를 구체적으로 쓰면 시험할 수 있다.',[['성공 조건',10],['재고 부족 조건',10],['중복 예약 조건',10]]),
 part('c','피드백 반영','essay',30,'시험 운영 중 재고가 실제와 다르다는 피드백을 받았다. 다음 반복 계획을 어떻게 조정할지 설명하시오.','재현 사례와 재고 갱신 경로를 조사해 결함인지 요구 차이인지 판단한다. 예약의 핵심 신뢰성 위험이므로 추천 기능보다 재고 일관성 개선을 우선한다. 요구·설계·테스트를 갱신하고 성공·동시 예약·취소 후 복구를 회귀 검증한 증분을 제공한다.','피드백을 검증 가능한 개선과 우선순위로 연결한다.',[['피드백 사실 확인',10],['위험·가치 기반 우선순위',10],['갱신·회귀·증분 전달',10]])]),
 task(6,16,'essay','architecture','서비스 경계의 이점과 비용','모놀리식 주문 시스템을 주문·결제·배송 서비스로 분리하려 한다. 얻을 수 있는 이점2가지와 새로 관리해야 할 복잡성2가지를 설명하시오.','서비스별 변경·배포를 분리하고 부하가 큰 기능을 독립적으로 확장할 수 있다. 반면 네트워크 지연·부분 실패를 처리해야 하며 여러 저장소의 데이터 일관성 및 분산 요청 추적이 복잡해진다. 단순히 분리했다고 품질이 개선되는 것은 아니므로 경계·운영 역량·업무 요구를 검토한다.','서비스 분리는 조직·배포 독립성과 분산 시스템 비용 사이의 선택이다.',[['독립 배포·확장 이점',10],['부분 실패·일관성 등 복잡성',15],['조건에 따른 선택 판단',5]]),
 task(6,17,'essay','architecture','중복 요청의 처리','고객이 결제 요청을 보냈지만 응답이 유실되어 재시도했다. 서버는 최초 결제를 이미 완료했다. 중복 결제를 막는 설계와 응답 유실 후 확인 방법을 설명하시오.','논리적으로 같은 결제에 동일한 요청 식별자를 사용한다. 서버는 식별자와 처리 상태·결과를 내구적으로 저장하고 식별자의 중복 처리를 원자적으로 막는다. 재시도에는 기존 결과를 반환한다. 처리 여부가 불확실하면 식별자로 상태를 조회해 확인하고 임의로 새 결제를 생성하지 않는다.','네트워크 응답 실패와 업무 처리 실패는 같지 않다. 멱등키와 원자적인 중복 통제가 필요하다.',[['응답 유실과 처리 완료 구분',10],['식별자·원자적 중복 방지',10],['결과 재사용·상태 확인',10]]),
 task(6,18,'code','design','계산 규칙 분리','Python subtotal(lines)을 작성하시오. lines는 price와 quantity를 가진 사전들의 리스트다. 단가는0 이상, 수량은1 이상이며 잘못된 항목은 ValueError를 발생시킨다. 합계를 반환하시오.','def subtotal(lines):\n    total = 0\n    for line in lines:\n        price, quantity = line["price"], line["quantity"]\n        if price < 0 or quantity < 1:\n            raise ValueError("invalid line")\n        total += price * quantity\n    return total','계산 규칙을 한 함수에 모으고 입력 검증을 계산 전에 수행한다. 빈 목록의 합계는0이다.',[['각 항목 접근·반복',10],['단가·수량 검증과 예외',20],['곱 합산 및 반환',15],['빈 목록0 처리',5]],{language:'python',starterCode:'def subtotal(lines):\n    pass'}),
 task(6,19,'diagram','architecture','계층 의존 구조','화면은 OrderService를 호출하고 OrderService는 OrderRepository를 호출한다. 화면에서 저장소로 직접 접근하지 않는다. 각각 submit(),place(),save() 공개 연산이 있다. 세 클래스를 의존 방향과 함께 그리시오.','Screen의 +submit(),OrderService의 +place(),OrderRepository의 +save()를 표시한다. Screen→OrderService→OrderRepository 의존선으로 연결하고 Screen→Repository 직접선을 그리지 않는다.','업무 계층을 통해 규칙을 적용하고 저장 구현의 영향을 화면에서 분리한다.',[['세 클래스·공개 연산',20],['화면에서 업무 계층 방향',15],['업무에서 저장소 방향·직접 우회 없음',15]],{modelDiagram:{nodes:[{id:'v',x:150,y:250,label:'Screen\n+submit(): void',shape:'class'},{id:'s',x:400,y:250,label:'OrderService\n+place(): void',shape:'class'},{id:'r',x:650,y:250,label:'OrderRepository\n+save(): void',shape:'class'}],edges:[{id:'vs',from:'v',to:'s',kind:'dependency'},{id:'sr',from:'s',to:'r',kind:'dependency'}]}}),
 task(6,20,'short','architecture','호출 예산 계산','순차 처리 A가40ms,B가70ms,C가30ms 걸리고 추가 오버헤드는 없다고 가정한다. 응답시간 상한150ms를 만족할 때 남은 여유시간을 ms 숫자로 쓰시오.','10','순차 소요시간40+70+30=140ms이며 여유는150-140=10ms다. 병렬 최대값으로 계산하면 안 된다.',[['순차 합140 계산',25],['상한과 차이10 계산',25]],{answer:'10',acceptedAnswers:['10','10ms','10 ms']}),
 integrated(6,'상품 조회 안정성','상품 조회는 필수 상품정보와 선택적인 추천정보를 반환한다. 추천 서버가 지연되면 전체 응답이 늦어진다. 상품 가격은 캐시에도 저장하며 가격 변경 직후 오래된 값이 보일 수 있다.','architecture',[
 part('a','지연 격리','essay',25,'추천 서버 장애가 상품 조회 전체로 번지지 않도록 방안을 설명하시오.','추천 호출에 제한시간을 정하고 실패하면 추천 없는 기본 화면을 반환한다. 재시도 횟수를 제한하고 지속 실패 시 호출 차단·복구 확인을 고려한다. 필수 상품 조회 자원과 선택 기능의 자원을 구분한다.','선택 기능의 실패를 핵심 기능으로 전파하지 않도록 한다.',[['제한시간·대체 결과',15],['재시도·자원/장애 격리',10]]),
 part('b','캐시 일관성','essay',25,'가격 변경 때 캐시와 결제 가격의 일관성을 어떻게 다룰지 설명하시오.','가격 변경 시 캐시 무효화·갱신과 만료 정책을 정한다. 화면 가격의 허용 지연을 명시하고 최종 결제 직전에는 신뢰 가능한 최신 가격을 확인해 변경을 사용자에게 알린다. 캐시를 유일한 원본으로 오인하지 않는다.','읽기 성능과 가격 정확성을 업무 단계별로 구분한다.',[['갱신·만료 전략',10],['결제 시 최신 검증·안내',15]]),
 part('c','검증 시나리오','essay',30,'장애·가격 변경을 포함한 검증 시나리오3가지를 기대 결과와 작성하시오.','추천 타임아웃 시 상품 기본 정보가 제한시간 내 표시되는지, 가격 변경 후 캐시가 정한 시간·규칙에 따라 갱신되는지, 화면 확인 뒤 가격이 바뀌면 결제 전 새 가격을 안내하고 승인 없이 잘못 결제하지 않는지 검증한다.','실패 경로와 시간차 데이터 변경까지 검증해야 한다.',[['타임아웃 시나리오',10],['캐시 갱신 시나리오',10],['결제 전 변경 시나리오',10]])]),

 task(7,16,'essay','language','스레드 실행과 대기','Java에서 Runnable, Thread, start(),run(),sleep()의 관계를 설명하시오. Thread.sleep(10000)을 작업 뒤에 호출하면 정확히 매10초 시작이 보장되는지도 설명하시오.','Runnable의 run은 수행할 작업을 정의하고 Thread는 이를 별도 실행 흐름에서 수행한다. start는 새 스레드 실행을 시작하며 run을 직접 호출하면 현재 스레드의 일반 호출이다. sleep(10000)은 현재 스레드의 실행을 대기시키지만 작업 시간과 스케줄링 지연을 제외하지 않는다. 따라서 작업 뒤10초 대기는 시작 간격이 정확히10초임을 보장하지 않는다.','실행 생성, 작업 정의, 대기 기능을 구분하고 고정 지연과 고정 주기를 혼동하지 않는다.',[['Runnable·Thread 관계',10],['start와run 차이',10],['sleep 단위와 정확한 주기 한계',10]]),
 task(7,17,'essay','language','공유 상태 경쟁','두 스레드가 공유 int counter를 각각1000번 증가시켰는데 최종값이2000보다 작다. 가능한 원인을 단계적으로 설명하고 해결책2가지를 제시하시오.','counter++는 읽기·증가·쓰기 단계로 생각할 수 있다. 두 스레드가 같은 이전값을 읽고 같은 새 값을 쓰면 한 번의 갱신이 사라진다. 같은 잠금으로 증가 구간을 보호하거나 원자적 증가를 제공하는 AtomicInteger 등을 사용한다. 단순히 대기시간을 넣는 방법은 동기화 보장이 아니다.','공유 복합 연산은 실행 순서가 겹칠 때 원자성이 깨질 수 있다.',[['읽기·쓰기 교차의 유실 예',15],['잠금과 원자 연산 대안',10],['대기만으로 해결 안 됨',5]]),
 task(7,18,'code','language','중단 가능한 수집 작업','Java Runnable 작업을 별도 스레드에서 시작하시오. 반복마다 collect()를 실행하고10초 대기한다. 인터럽트 시 종료하며 중단 상태를 복원하시오. collect()는 이미 정의된 static 메서드라고 가정한다.','Runnable job = () -> {\n    while (!Thread.currentThread().isInterrupted()) {\n        collect();\n        try {\n            Thread.sleep(10000);\n        } catch (InterruptedException e) {\n            Thread.currentThread().interrupt();\n            break;\n        }\n    }\n};\nThread worker = new Thread(job);\nworker.start();','InterruptedException을 출력만 하고 무시하면 종료 요청을 잃을 수 있다. 상태 복원 후 반복을 빠져나간다.',[['Runnable·반복 수집',10],['10000밀리초 대기',10],['예외 시 인터럽트 복원·종료',20],['Thread 생성·start',10]],{language:'java',starterCode:'// main 메서드 안에 들어갈 코드를 작성하세요.\n// collect()는 이미 구현되어 있습니다.'}),
 task(7,19,'diagram','activity','정상 처리와 실패 처리','파일을 연 뒤 내용을 읽는다. 읽기 성공이면 결과를 표시하고 실패이면 오류를 기록한다. 어느 경로든 열린 파일을 닫고 종료한다. 성공 여부 분기로 단순화한 활동도를 그리시오.','시작→파일열기→읽기시도→성공? [예] 결과표시, [아니요] 오류기록→병합→파일닫기→종료.','공통 정리 동작은 두 경로가 모인 뒤 실행하도록 나타낸다.',[['열기·읽기 순서',10],['성공·실패 두 경로',15],['두 경로 병합 후 닫기',20],['시작·종료',5]],{modelDiagram:{nodes:[{id:'s',x:400,y:20,shape:'start',label:'시작'},{id:'o',x:400,y:80,shape:'action',label:'파일 열기'},{id:'r',x:400,y:150,shape:'action',label:'읽기 시도'},{id:'d',x:400,y:230,shape:'decision',label:'읽기 성공?'},{id:'y',x:170,y:320,shape:'action',label:'결과 표시'},{id:'n',x:630,y:320,shape:'action',label:'오류 기록'},{id:'m',x:400,y:400,shape:'decision',label:''},{id:'c',x:400,y:475,shape:'action',label:'파일 닫기'},{id:'f',x:400,y:560,shape:'end',label:'종료'}],edges:[{id:'1',from:'s',to:'o'},{id:'2',from:'o',to:'r'},{id:'3',from:'r',to:'d'},{id:'4',from:'d',to:'y',label:'[예]'},{id:'5',from:'d',to:'n',label:'[아니요]'},{id:'6',from:'y',to:'m'},{id:'7',from:'n',to:'m'},{id:'8',from:'m',to:'c'},{id:'9',from:'c',to:'f'}]}}),
 task(7,20,'short','language','복사와 참조의 결과','Python에서 a=[1,2]; b=a; c=a.copy(); b.append(3); c.append(4)를 실행한다. a의 최종값을 쓰시오.','[1,2,3]','b는 a와 같은 리스트를 가리키지만 c는 별도 리스트 복사본이다. b의 추가는 a에 보이고 c의 추가는 a에 영향을 주지 않는다.',[['b의 별칭 이해',20],['c의 복사본 이해',20],['최종 목록',10]],{answer:'[1,2,3]',acceptedAnswers:['[1,2,3]','[1, 2, 3]','1,2,3']}),
 integrated(7,'센서 값의 집계','센서에서 수신한 문자열 목록 중 정수로 변환 가능한 값만 평균에 포함한다. 유효 값이 하나도 없으면 None을 반환한다. 빈 문자열과 "ERR"는 변환 실패 예다.','language',[
 part('a','정상 결과','short',20,'입력 ["10","ERR","20",""]에 대한 평균을 쓰시오.','15','유효한10과20의 합30을2개로 나눈다.',[['유효값10·20만 선택',10],['평균15',10]],{answer:'15',acceptedAnswers:['15','15.0']}),
 part('b','집계 구현','code',40,'Python average_valid(values)를 작성하시오.','def average_valid(values):\n    numbers = []\n    for text in values:\n        try:\n            numbers.append(int(text))\n        except ValueError:\n            continue\n    if not numbers:\n        return None\n    return sum(numbers) / len(numbers)','변환 성공한 값만 분모·분자에 포함하고0개일 때 나눗셈을 피한다.',[['ValueError 처리·유효값 수집',20],['유효값0개 None',10],['올바른 평균',10]],{language:'python'}),
 part('c','검증 계획','essay',20,'정상·실패·빈 입력을 포괄하는 테스트3개와 예상값을 제시하시오.','["2","4"]→3.0, ["ERR","6"]→6.0, []→None을 확인한다. 모두 무효인 ["ERR",""]→None도 추가하면 좋다.','입력 오류를 제거한 뒤의 분모와 빈 경우를 함께 확인한다.',[['정상·혼합 테스트',10],['빈 또는 모두 무효 테스트',10]])]),

 task(8,16,'essay','config','추적 가능한 출시','운영 장애가 발생했는데 배포 파일과 소스 버전의 연결을 알 수 없다. 재현·복구를 위해 관리할 정보를4가지 이상 설명하시오.','소스 커밋·태그, 의존 라이브러리 버전, 빌드 도구·런타임 버전, 빌드·테스트 결과, 산출물 식별자·체크섬, 배포 환경과 설정 버전, 배포 시각을 연결한다. 이전 정상 산출물과 호환되는 데이터 변경 여부를 확인해 복구 계획을 세운다. 비밀값 자체를 공개 이력에 넣지는 않는다.','운영 산출물의 재현 가능한 출처와 복구 가능한 기준선을 함께 관리한다.',[['식별·빌드 정보2가지 이상',10],['환경·배포·검증 정보2가지 이상',10],['정상 기준선과 복구 고려',10]]),
 task(8,17,'essay','maintenance','유지보수 분류','①잘못된 할인율 수정 ②새 OS에 맞춘 경로 수정 ③고객 요청으로 검색 기능 추가 ④미래 결함을 줄이기 위한 복잡한 코드 정리를 각각 유지보수 유형으로 분류하고 이유를 설명하시오.','①수정: 발견된 결함을 바로잡는다.②적응: 실행 환경 변화에 맞춘다.③완전: 사용자 요구에 따른 기능을 개선한다.④예방: 앞으로의 장애와 유지 부담을 줄인다. 하나의 변경에 목적이 겹칠 수 있으나 이 사례에서는 제시된 주목적을 따른다.','변경의 원인과 목적을 기준으로 분류한다.',[['수정·적응 분류와 이유',15],['완전·예방 분류와 이유',15]]),
 task(8,18,'code','config','변경 모듈 추적','Python impacted(changed,links)를 작성하시오. changed는 변경 요구 ID 목록, links는 요구 ID에서 모듈 ID 목록으로의 사전이다. 관련 모듈을 중복 없이 정렬한 리스트로 반환하며 연결이 없는 요구는 무시한다.','def impacted(changed, links):\n    modules = set()\n    for requirement in changed:\n        modules.update(links.get(requirement, []))\n    return sorted(modules)','집합으로 중복을 제거하고 get의 기본값으로 미등록 요구를 안전하게 처리한다.',[['변경 요구별 연결 조회',15],['미등록 요구 처리',10],['집합 중복 제거',15],['정렬 반환',10]],{language:'python',starterCode:'def impacted(changed, links):\n    pass'}),
 task(8,19,'diagram','process','병렬 검증 파이프라인','소스 준비 후 단위 테스트와 정적 분석을 병렬로 수행한다. 둘 다 완료되어야 패키지를 생성하고 종료한다. 여기서는 실패가 없다고 가정한다. 활동도에 fork와 join을 표시하시오.','시작→소스준비→fork→단위테스트 / 정적분석 병렬→join→패키지생성→종료.','병렬 작업 시작은 fork, 모두 완료한 동기화는 join이며 선택·병합 마름모와 다르다.',[['준비·패키지 순서',10],['fork에서 두 병렬 경로',15],['join에서 두 완료 대기',20],['시작·종료',5]],{modelDiagram:{nodes:[{id:'s',x:400,y:20,label:'시작',shape:'start'},{id:'a',x:400,y:100,label:'소스 준비',shape:'action'},{id:'fork',x:400,y:190,label:'fork',shape:'bar'},{id:'t',x:200,y:285,label:'단위 테스트',shape:'action'},{id:'l',x:600,y:285,label:'정적 분석',shape:'action'},{id:'join',x:400,y:380,label:'join',shape:'bar'},{id:'p',x:400,y:460,label:'패키지 생성',shape:'action'},{id:'f',x:400,y:550,label:'종료',shape:'end'}],edges:[{id:'1',from:'s',to:'a'},{id:'2',from:'a',to:'fork'},{id:'3',from:'fork',to:'t'},{id:'4',from:'fork',to:'l'},{id:'5',from:'t',to:'join'},{id:'6',from:'l',to:'join'},{id:'7',from:'join',to:'p'},{id:'8',from:'p',to:'f'}]}}),
 task(8,20,'short','process','검증 완료 시간','소스 준비2분 뒤 테스트6분과 정적 분석4분을 동시에 시작한다. 둘 다 끝나면 패키징3분을 수행한다. 오버헤드가 없다면 전체 소요시간은 몇 분인가?','11','2+max(6,4)+3=11분이다. 병렬 구간은 두 시간의 합이 아닌 더 긴 시간만큼 기다린다.',[['병렬 최대값6',25],['전후 단계 합11',25]],{answer:'11',acceptedAnswers:['11','11분']}),
 integrated(8,'레거시 모듈 개선','문서 없는 레거시 계산 모듈에 중복과 전역 상태가 많다. 기능을 유지하며 개선하고 여러 팀의 공통 모듈로 배포하려 한다.','reuse',[
 part('a','현행 분석','essay',25,'코드를 수정하기 전에 수행할 분석과 확인 방법을 설명하시오.','입출력·호출 관계·전역 상태·예외 동작을 분석해 구조를 복원한다. 실제 업무 사례와 로그를 확인하고 현재 동작을 고정하는 특성 테스트를 작성한다. 결함으로 확인된 동작과 유지해야 할 계약을 구분한다.','역공학으로 구조를 이해하고 변경 전 동작 근거를 확보한다.',[['구조·입출력 분석',10],['현행 테스트·계약 확인',15]]),
 part('b','개선 순서','essay',30,'위험을 줄이는 리팩토링 순서와 공유 모듈의 인터페이스 원칙을 제안하시오.','작은 단위로 중복 규칙을 함수로 추출하고 전역 상태를 명시적 인자·의존 객체로 바꾼다. 매 단계 회귀 테스트를 실행한다. 공통 인터페이스는 필요한 입력·결과·오류 계약만 공개하고 내부 자료 구조를 숨긴다.','작은 변경과 검증으로 기능 보존을 확인하며 결합을 낮춘다.',[['단계적 추출·전역 의존 축소',15],['회귀·인터페이스 계약',15]]),
 part('c','배포 통제','essay',25,'공통 모듈 변경을 소비 팀이 안전하게 받아들이도록 필요한 정보를 설명하시오.','버전·변경 이력·호환성 범위·마이그레이션 안내와 테스트 근거를 제공한다. 특정 버전 의존을 기록하고 소비 서비스의 계약·통합 테스트를 수행한다. 문제가 생기면 검증한 이전 버전으로 복구할 경로를 확보한다.','재사용 컴포넌트는 변경 영향이 여러 소비자에게 퍼진다.',[['버전·호환성·변경 정보',15],['소비자 검증·복구',10]])]),

 task(9,16,'essay','ux','사용자 오류의 개선','입력 폼이 필수 항목을 색으로만 표시하고, 제출 실패 시 “오류”만 표시하며, 입력값도 모두 지운다. 문제3가지와 대응3가지를 연결해 설명하시오.','색만으로 구분하면 색을 인지하기 어려운 사용자가 필수를 놓치므로 텍스트·기호를 함께 쓴다. 오류라는 말만 있으면 수정 방법을 모르므로 문제 필드와 허용 형식·예를 제시한다. 값을 모두 지우면 재입력 부담이 생기므로 유효한 입력을 보존하고 오류 필드로 안내한다.','접근성·회복 가능성·작업 부담을 각각 개선한다.',[['색 의존과 대체 표시',10],['오류 설명과 수정 안내',10],['입력 보존과 회복 지원',10]]),
 task(9,17,'essay','opensource','외부 컴포넌트 도입','인터넷에 공개된 코드와 오픈소스 라이선스로 배포된 코드가 같은 의미인지 설명하고, 라이브러리 도입 전 확인할 사항4가지를 제시하시오.','공개되어 읽을 수 있다는 사실만으로 수정·재배포 권한이 보장되지는 않는다. 명시된 라이선스와 적용 범위를 확인한다. 도입 전 이용·배포 의무, 취약점과 업데이트 상태, 기술·플랫폼 호환성, 유지보수 커뮤니티, 의존 버전과 출처 등을 검토한다. 배포 형태에 따라 구체적인 의무가 달라질 수 있다.','공개 접근과 이용 허락을 구분하고 기술·운영 조건도 함께 평가한다.',[['공개와 라이선스의 차이',10],['권한·의무 검토',10],['기술·보안·유지 상태 등3가지',10]]),
 task(9,18,'code','object','알고리즘 주입','Python Checkout이 전달받은 price_policy 함수를 저장하고 total(price)에서 그 함수를 호출하도록 작성하시오. 생성자에서 전달하지 않으면 원래 가격을 반환하는 기본 정책을 사용하시오.','class Checkout:\n    def __init__(self, price_policy=None):\n        self.price_policy = price_policy if price_policy is not None else lambda price: price\n\n    def total(self, price):\n        return self.price_policy(price)','계산 행동을 호출 가능한 객체로 분리하면 Checkout 수정 없이 정책을 교체할 수 있다.',[['생성자와 정책 보관',15],['None일 때 기본 정책',15],['total의 위임·반환',20]],{language:'python',starterCode:'class Checkout:\n    def __init__(self, price_policy=None):\n        pass\n\n    def total(self, price):\n        pass'}),
 task(9,19,'diagram','object','변경 통지의 구조','추상 Listener에는 public update(message:String):void가 있다. LogListener가 이를 구현한다. NotificationCenter는0개 이상의 Listener를 참조하고 public subscribe(listener:Listener):void로 등록한다. 속성·연산과 관계를 클래스 다이어그램으로 그리시오. 수명 소유는 가정하지 않는다.','Listener의 추상 update와 LogListener의 구현을 표시하고 LogListener에서 Listener로 일반화한다. NotificationCenter에는 Listener 목록과 subscribe를 표시하고 Listener로0..* 참조 관계를 연결한다.','알림 중심 객체의 참조 관계와 구체 리스너의 상속 관계를 구분한다.',[['추상·구체 Listener와 연산',20],['일반화 방향',10],['Center 목록·등록 연산과0..* 연관',20]],{modelDiagram:{nodes:[{id:'l',x:480,y:120,label:'Listener {abstract}\n+update(m:String):void\n{abstract}',shape:'class'},{id:'c',x:170,y:350,label:'NotificationCenter\n-listeners: List<Listener>\n+subscribe(l:Listener):void',shape:'class'},{id:'g',x:610,y:410,label:'LogListener\n+update(m:String):void',shape:'class'}],edges:[{id:'g-l',from:'g',to:'l',kind:'inheritance'},{id:'c-l',from:'c',to:'l',kind:'arrow',label:'0..*'}]}}),
 task(9,20,'short','object','위임 함수의 결과','위 Checkout에 lambda p: max(0,p-500)을 주입한다. total(300)의 결과는?','0','정책 계산은300-500=-200이지만 하한0을 적용한다.',[['주입 정책 호출 이해',20],['차감·하한 계산',20],['결과0',10]],{answer:'0',acceptedAnswers:['0']}),
 integrated(9,'알림 기능의 확장','주문 완료를 이메일로 알리던 서비스를 문자·앱 알림으로 확장한다. 화면은 실패 원인을 이해할 수 있어야 하며 발송 방식별 세부 구현을 주문 코드에 퍼뜨리지 않으려 한다.','object',[
 part('a','책임 분리','essay',30,'주문·알림 기능의 클래스 책임과 의존 방향을 제안하시오.','주문 서비스는 주문 처리와 알림 요청 시점을 맡고 Sender 계약에 의존한다. 이메일·문자·앱 구현은 각 통신 형식을 맡는다. 어떤 구현을 사용할지는 외부 설정·조립 지점에서 결정한다.','변경 이유가 다른 주문 규칙과 발송 기술을 분리한다.',[['주문·발송 책임 분리',15],['추상 계약·외부 구성',15]]),
 part('b','테스트 대체','code',30,'Python FakeSender를 작성하시오. 생성 시 sent를 빈 리스트로 만들고 send(message)가 호출되면 메시지를 기록한다. 실제 네트워크는 사용하지 않는다.','class FakeSender:\n    def __init__(self):\n        self.sent = []\n\n    def send(self, message):\n        self.sent.append(message)','테스트는 sent를 검사해 주문 완료 때 올바른 알림이 요청됐는지 확인할 수 있다.',[['인스턴스별 빈 리스트',15],['메시지 기록·외부 호출 없음',15]],{language:'python'}),
 part('c','실패 안내','essay',20,'알림 발송 실패가 이미 완료된 주문을 실패처럼 보이게 만들지 않도록 사용자 메시지와 처리 상태를 제안하시오.','“주문은 완료되었습니다. 알림 발송에 실패해 다시 시도합니다.”처럼 두 상태를 구분한다. 주문번호를 제공하고 알림 상태·재시도 결과를 별도로 관리한다. 내부 오류코드만 보여주거나 주문이 사라진 것처럼 표시하지 않는다.','업무 완료와 부가 알림 실패를 구분해 사용자의 중복 주문을 예방한다.',[['주문·알림 상태 구분',10],['구체 안내·재시도 상태',10]])]),

 task(10,16,'essay','design','공통 규칙의 재설계','화면·API·배치마다 복사한 할인 코드가 서로 다르게 수정되었다. 중복의 문제를 설명하고 단일 규칙·인터페이스·테스트 관점에서 개선안을 제안하시오.','동일 정책의 사본이 서로 달라져 같은 주문의 금액이 경로별로 달라질 수 있다. 계산 규칙을 공통 모듈로 모으고 각 경로는 명확한 입력·반환·오류 계약으로 호출한다. 정책별 단위 테스트와 각 호출 경로의 통합 테스트를 유지한다. 공통 변경의 영향 범위를 추적해 검증하고 버전을 관리한다.','중복 제거는 코드 줄 수보다 업무 의미의 일관성 확보가 목적이다.',[['사본 불일치 문제',10],['공통 규칙·계약 설계',10],['단위·통합 검증 및 영향 관리',10]]),
 task(10,17,'essay','test','출시 판단의 근거','새 예약 기능의 단위 테스트는 통과했지만 동시 예약·장애 복구·사용자 인수는 확인하지 않았다. 추가 검증3가지를 구체적인 실패 위험과 연결해 제안하시오.','동시 요청으로 마지막 좌석이 중복 확정되지 않는지 통합·동시성 테스트한다. 저장·결제 중 실패와 재시도에서 중복 처리나 반쪽 상태가 생기지 않는지 장애 복구를 확인한다. 대표 사용자가 검색·예약·취소 흐름을 수행해 인수 조건과 사용성을 검증한다. 단위 통과만으로 이런 환경·흐름의 계약은 보장되지 않는다.','출시 판단은 실제 업무와 실패 경로를 포함한 여러 수준의 근거가 필요하다.',[['동시성 위험·시험',10],['부분 실패·재시도 시험',10],['업무 인수·사용성 시험',10]]),
 task(10,18,'code','algorithm','검색 함수 작성','오름차순 정수 리스트 values에서 target을 찾는 Python binary_search를 작성하시오. 존재하면 해당 인덱스 하나, 없으면 -1을 반환한다. 중복 값은 어떤 일치 인덱스라도 허용한다.','def binary_search(values, target):\n    low, high = 0, len(values) - 1\n    while low <= high:\n        mid = low + (high - low) // 2\n        if values[mid] == target:\n            return mid\n        if values[mid] < target:\n            low = mid + 1\n        else:\n            high = mid - 1\n    return -1','양끝 포함 구간을 유지하고 중간 원소를 제외해 줄여야 무한 반복을 피한다. 빈 리스트는 바로-1을 반환한다.',[['초기 구간·반복 조건',10],['중간값·일치 반환',15],['mid±1 구간 축소',20],['미발견-1',5]],{language:'python',starterCode:'def binary_search(values, target):\n    pass'}),
 task(10,19,'diagram','activity','예약 취소의 대안 흐름','예약 취소를 요청하면 취소 가능 여부를 확인한다. 가능하면 예약 취소와 환불 요청을 순서대로 수행한다. 불가능하면 거절 사유를 표시한다. 어느 경로든 처리 결과 표시 후 종료한다. 활동도를 그리시오.','시작→취소요청→가능? [예] 예약취소→환불요청, [아니요] 거절사유표시. 병합→처리결과표시→종료.','같은 경로의 순차 행동과 대안 경로의 병합을 구별한다.',[['요청·가능 여부 결정',10],['취소→환불 순서',15],['거절 경로·가드',10],['병합 후 공통 결과·종료',15]],{modelDiagram:{nodes:[{id:'s',x:400,y:20,label:'시작',shape:'start'},{id:'q',x:400,y:85,label:'취소 요청',shape:'action'},{id:'d',x:400,y:175,label:'취소 가능?',shape:'decision'},{id:'c',x:170,y:275,label:'예약 취소',shape:'action'},{id:'r',x:170,y:355,label:'환불 요청',shape:'action'},{id:'n',x:630,y:310,label:'거절 사유 표시',shape:'action'},{id:'m',x:400,y:405,label:'',shape:'decision'},{id:'o',x:400,y:480,label:'처리 결과 표시',shape:'action'},{id:'f',x:400,y:560,label:'종료',shape:'end'}],edges:[{id:'1',from:'s',to:'q'},{id:'2',from:'q',to:'d'},{id:'3',from:'d',to:'c',label:'[예]'},{id:'4',from:'c',to:'r'},{id:'5',from:'d',to:'n',label:'[아니요]'},{id:'6',from:'r',to:'m'},{id:'7',from:'n',to:'m'},{id:'8',from:'m',to:'o'},{id:'9',from:'o',to:'f'}]}}),
 task(10,20,'short','algorithm','반복 출력의 계산','다음 Python 코드에서 count의 최종값을 구하시오.\ncount=0\nfor i in range(4):\n    for j in range(i):\n        count += 1','6','i=0,1,2,3일 때 안쪽 반복은 각각0,1,2,3번이므로 합계6이다.',[['range(4)의 값0..3',15],['안쪽 반복0·1·2·3',20],['합계6',15]],{answer:'6',acceptedAnswers:['6']}),
 integrated(10,'예약 규칙의 구현과 검증','예약 시스템은 같은 사용자·같은 회차의 중복 예약을 거부한다. 요청은 user와session을 가진 사전이며, 이미 처리한 키들의 집합을 전달받는다. 단일 스레드의 연습 코드로 작성한다. 운영 환경에서는 동시 요청이 있을 수 있다.','design',[
 part('a','키 설계','short',20,'사용자u1의 회차s2 예약을 구분하는 Python 튜플 키를 쓰시오.','("u1", "s2")','사용자만 또는 회차만으로는 서로 다른 예약을 구별하지 못한다.',[['사용자·회차 포함',10],['해시 가능한 튜플 구성',10]],{answer:'("u1", "s2")',acceptedAnswers:['("u1", "s2")','("u1","s2")',"('u1', 's2')","('u1','s2')"]}),
 part('b','연습 코드','code',35,'reserve(request,seen)를 작성하시오. 키가 이미 있으면 False, 없으면 seen에 추가하고 True를 반환한다.','def reserve(request, seen):\n    key = (request["user"], request["session"])\n    if key in seen:\n        return False\n    seen.add(key)\n    return True','단일 스레드 조건에서는 확인 후 추가로 중복을 방지할 수 있다.',[['복합 키 구성',10],['기존 키 거부',10],['새 키 추가·반환',15]],{language:'python'}),
 part('c','동시성 한계','essay',25,'이 코드의 확인과 추가가 여러 요청에서 동시에 실행된다면 어떤 문제가 가능하고 어떻게 보완해야 하는가?','두 요청이 모두 키가 없다고 확인한 뒤 각각 성공 처리할 수 있다. 운영 저장소의 고유 제약·트랜잭션 또는 동일 키에 대한 원자적인 확인·등록을 사용해 경쟁을 막는다. 애플리케이션의 사전 검사만으로 유일성을 보장했다고 생각하면 안 된다.','단일 스레드 연습의 성공이 동시 운영 환경의 원자성 보장을 뜻하지 않는다.',[['확인-추가 경합 설명',10],['고유 제약·원자적 처리 대안',15]])]),
];
